"""Update Two-Vault models with encrypted fields and merged Behavioral Vault

Revision ID: a2482c99d090
Revises: acd6dd4e1b02
Create Date: 2026-10-08 19:27:42.200941

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'a2482c99d090'
down_revision: Union[str, None] = 'acd6dd4e1b02'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_identity_mappings_email'), table_name='identity_mappings')
    op.drop_index(op.f('ix_identity_mappings_github_username'), table_name='identity_mappings')
    op.drop_index(op.f('ix_identity_mappings_hrms_employee_id'), table_name='identity_mappings')
    op.add_column('weekly_employee_metrics', sa.Column('probability_low', sa.Float(), nullable=True))
    op.add_column('weekly_employee_metrics', sa.Column('probability_medium', sa.Float(), nullable=True))
    op.add_column('weekly_employee_metrics', sa.Column('probability_high', sa.Float(), nullable=True))
    op.add_column('weekly_employee_metrics', sa.Column('shap_explanations', sa.String(), nullable=True))
    op.add_column('weekly_employee_metrics', sa.Column('model_version', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('weekly_employee_metrics', 'model_version')
    op.drop_column('weekly_employee_metrics', 'shap_explanations')
    op.drop_column('weekly_employee_metrics', 'probability_high')
    op.drop_column('weekly_employee_metrics', 'probability_medium')
    op.drop_column('weekly_employee_metrics', 'probability_low')
    op.create_index(op.f('ix_identity_mappings_hrms_employee_id'), 'identity_mappings', ['hrms_employee_id'], unique=1)
    op.create_index(op.f('ix_identity_mappings_github_username'), 'identity_mappings', ['github_username'], unique=1)
    op.create_index(op.f('ix_identity_mappings_email'), 'identity_mappings', ['email'], unique=1)
    # ### end Alembic commands ###
