"""Add Two-Vault models

Revision ID: acd6dd4e1b02
Revises: 9d80c91efef7
Create Date: 2026-10-08 19:11:25.940414

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'acd6dd4e1b02'
down_revision: Union[str, None] = '9d80c91efef7'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('burnout_predictions',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('employee_hash', sa.String(), nullable=False),
    sa.Column('week_start_date', sa.Date(), nullable=False),
    sa.Column('predicted_risk', sa.String(), nullable=False),
    sa.Column('probability_low', sa.Float(), nullable=False),
    sa.Column('probability_medium', sa.Float(), nullable=False),
    sa.Column('probability_high', sa.Float(), nullable=False),
    sa.Column('shap_explanations', sa.String(), nullable=True),
    sa.Column('model_type', sa.String(), nullable=False),
    sa.Column('model_version', sa.String(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('employee_hash', 'week_start_date', 'model_version', name='uq_prediction_week_version')
    )
    op.create_index(op.f('ix_burnout_predictions_employee_hash'), 'burnout_predictions', ['employee_hash'], unique=False)
    op.create_index(op.f('ix_burnout_predictions_id'), 'burnout_predictions', ['id'], unique=False)
    op.create_table('identity_mappings',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('employee_hash', sa.String(), nullable=False),
    sa.Column('email', sa.String(), nullable=True),
    sa.Column('github_username', sa.String(), nullable=True),
    sa.Column('hrms_employee_id', sa.String(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_identity_mappings_email'), 'identity_mappings', ['email'], unique=True)
    op.create_index(op.f('ix_identity_mappings_employee_hash'), 'identity_mappings', ['employee_hash'], unique=True)
    op.create_index(op.f('ix_identity_mappings_github_username'), 'identity_mappings', ['github_username'], unique=True)
    op.create_index(op.f('ix_identity_mappings_hrms_employee_id'), 'identity_mappings', ['hrms_employee_id'], unique=True)
    op.create_index(op.f('ix_identity_mappings_id'), 'identity_mappings', ['id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_identity_mappings_id'), table_name='identity_mappings')
    op.drop_index(op.f('ix_identity_mappings_hrms_employee_id'), table_name='identity_mappings')
    op.drop_index(op.f('ix_identity_mappings_github_username'), table_name='identity_mappings')
    op.drop_index(op.f('ix_identity_mappings_employee_hash'), table_name='identity_mappings')
    op.drop_index(op.f('ix_identity_mappings_email'), table_name='identity_mappings')
    op.drop_table('identity_mappings')
    op.drop_index(op.f('ix_burnout_predictions_id'), table_name='burnout_predictions')
    op.drop_index(op.f('ix_burnout_predictions_employee_hash'), table_name='burnout_predictions')
    op.drop_table('burnout_predictions')
    # ### end Alembic commands ###
