"""Rename probability fields in BurnoutPrediction

Revision ID: e4ae969e0060
Revises: 2932bc63dabd
Create Date: 2026-10-08 21:35:18.337464

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'e4ae969e0060'
down_revision: Union[str, None] = '2932bc63dabd'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('burnout_predictions', sa.Column('low_probability', sa.Float(), nullable=False))
    op.add_column('burnout_predictions', sa.Column('medium_probability', sa.Float(), nullable=False))
    op.add_column('burnout_predictions', sa.Column('high_probability', sa.Float(), nullable=False))
    op.drop_column('burnout_predictions', 'probability_medium')
    op.drop_column('burnout_predictions', 'probability_low')
    op.drop_column('burnout_predictions', 'probability_high')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('burnout_predictions', sa.Column('probability_high', sa.FLOAT(), nullable=False))
    op.add_column('burnout_predictions', sa.Column('probability_low', sa.FLOAT(), nullable=False))
    op.add_column('burnout_predictions', sa.Column('probability_medium', sa.FLOAT(), nullable=False))
    op.drop_column('burnout_predictions', 'high_probability')
    op.drop_column('burnout_predictions', 'medium_probability')
    op.drop_column('burnout_predictions', 'low_probability')
    # ### end Alembic commands ###
